name: Handle Repository Dispatch

on:
  repository_dispatch:
    types: [trigger-workflow]

jobs:
  process:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Process dispatch
        run: |
          echo "Triggered by: ${{ github.event.client_payload.source_repo }}"
          echo "Event type: ${{ github.event.action }}"
          echo "Additional data: ${{ github.event.client_payload.data }}"