name: Handle Docs

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger-workflow, pull-request-closed]

jobs:
  process:
    if: ${{ github.event.client_payload.source_repo == 'Ensosuru/docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Process dispatch
        run: |
          echo "Triggered by: ${{ github.event.client_payload.source_repo }}"
          echo "Event type: ${{ github.event.action }}"
          echo "ref: ${{ github.event.client_payload.ref }}"
          echo "sha: ${{ github.event.client_payload.sha }}",
          echo "other: ${{ github.event.client_payload.other }}",
          echo "pr number: ${{ github.event.client_payload.pr_number }}"
          echo "pr label: ${{ github.event.client_payload.pr_label }}"

      - name: Generate token
        id: generate_token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: docs

      - name: Comment on issue
        if: ${{ github.event.client_payload.pr_number != '' || github.event.client_payload.pr_number != null }}
        uses: actions/github-script@v8
        with:
          github-token: ${{ steps.generate_token.outputs.token }}
          script: |
            github.rest.issues.createComment({
              issue_number: ${{ github.event.client_payload.pr_number }},
              owner: 'Ensosuru',
              repo: 'docs',
              body: 'Comment from github-script action!'
            })